### ISSUE TITLE
Listen together feature

### ISSUE THREAD

**Issue by Davoleo** [Vendicated/PowercordPlayOnSpotify#1]
Hey any chance this pluging could unlock spotify listen together feature?
I know it's a pretty _borderline_ topic, but I recall someone doing this kind of monkey-patch before 🤔 

feel free to close this request if it's not feasible or you just don't want to develop it

Reference that made me aware that someone did this before for BD: https://github.com/mrpond/BlockTheSpot (issue-76)

**Comment by Vendicated** [comment]
That is against the Spotify ToS and also not related at all to the purpose of this plugin
